### ISSUE TITLE
The venue section : come up with something so that we can use it 

### ISSUE THREAD

**Issue by Chaitya62** [KJSCE-Codecell/kjsce-codecell.github.io#13]
The venue section is not really relevant as of now come up with something for that section and make chagnes accordingly @vedipen  if there is plans for that section close this issue and make another one suggesting the changes

**Comment by vedipen** [comment]
Will add "upcoming workshop" to it..and link it to KJSCE location.

**Comment by Chaitya62** [comment]
Sound cool! just the maps api doesn't seem to work

**Comment by vedipen** [comment]
The map comes for a sec and then gives error :/

**Comment by vedipen** [comment]
0df992e7ae6b085aeaa6e31a5dbcb7d91b56a936 closes this.
