### ISSUE TITLE
Add tag for Post in Agenda

### ISSUE THREAD

**Issue by vedipen** [KJSCE-Codecell/kjsce-codecell.github.io#9]
#7 removed the tags in Agenda. We need them to represent as the post of the respective members of the committee below it. Should look the same as it was before but we need to add such more tags (4 in total).

**Comment by Chaitya62** [comment]
is this done? please close the issue if so

**Comment by vedipen** [comment]
No it is not. Check OUR TEAM, we need those yellow tags which @sagard116 removed.
Please understand the issue correctly before commenting. xD

**Comment by sagard116** [comment]
Arey for post there is a heading available dekh faculty advisor daala hai na vaise sab me we can have post

**Comment by vedipen** [comment]
Not a nice idea. Tags look great. Plus you removed those time listing too. Why remove everything? We could have added some interesting taglines there. What say? @sagard116

**Comment by vedipen** [comment]
#27 closes this
